// Live preview for the Artifact Viewer. Embeds the generated
// scaffold inside a StackBlitz WebContainer iframe — gives partners
// both a runnable preview AND an editable Monaco-style editor in
// the same surface (no need for a separate code-edit tab).
//
// We use the `node` template for everything because the scaffolds
// Inspira generates are vite/npm-driven; StackBlitz auto-detects
// the start script from package.json.

import { ReactElement, useEffect, useRef, useState } from "react";
import sdk, { type VM } from "@stackblitz/sdk";

import type { ArtifactFile } from "../api";

export interface StackBlitzPreviewProps {
  files: ArtifactFile[];
  /** Inspira's framework slug — `react-vite` / `node` / etc. Used
   *  only as a hint; we mostly route through `node` since modern
   *  scaffolds are package.json-driven. */
  framework?: string | null;
  /** When the viewer's chat refines the scaffold the files array
   *  changes identity — bump this so the embed re-mounts cleanly
   *  rather than diff-and-reapply (StackBlitz's `applyFsDiff` is
   *  more complex than the demo needs). */
  scaffoldId?: string | null;
  /** When true, the embed mounts in preview-only mode — the editor
   *  pane is hidden and the user can only interact with the running
   *  app. Wired by ArtifactViewerPage when project_state ≠ draft. */
  readOnly?: boolean;
}

export function StackBlitzPreview({
  files,
  framework,
  scaffoldId,
  readOnly,
}: StackBlitzPreviewProps): ReactElement {
  const containerRef = useRef<HTMLDivElement>(null);
  const vmRef = useRef<VM | null>(null);
  const [embedError, setEmbedError] = useState<string | null>(null);

  useEffect(() => {
    const outer = containerRef.current;
    if (!outer || files.length === 0) return;

    // CRITICAL: sdk.embedProject REPLACES the passed element with the
    // StackBlitz iframe. If we pass `containerRef.current` directly,
    // React's virtual DOM still thinks our outer div exists when the
    // SDK has actually swapped it for an iframe. The next React
    // render (e.g. Preview → Code switch) then tries to reconcile a
    // div that no longer exists and either renders nothing or
    // crashes with a "Failed to execute 'removeChild'" error
    // depending on the React version.
    //
    // Fix: create an unmanaged inner div, append it under our
    // React-owned outer div, and pass THAT inner div to the SDK.
    // The SDK replaces the inner div with the iframe; React's outer
    // ref stays untouched and reconciles correctly across renders.
    const target = document.createElement("div");
    target.style.width = "100%";
    target.style.height = "100%";
    outer.appendChild(target);

    const filesMap: Record<string, string> = {};
    for (const f of files) {
      filesMap[f.path] = f.content;
    }

    let cancelled = false;
    setEmbedError(null);

    sdk
      .embedProject(
        target,
        {
          title: "Inspira scaffold",
          description: readOnly
            ? "Generated by Inspira — read-only (project is in review or approved)."
            : "Generated by Inspira — edit + preview live.",
          template: mapFrameworkToTemplate(framework),
          files: filesMap,
        },
        {
          // preview-only when the project is past draft; default split
          // (editor + preview) when it's still editable.
          view: readOnly ? "preview" : "default",
          height: "100%",
          hideExplorer: readOnly,
          hideNavigation: true,
          forceEmbedLayout: true,
        },
      )
      .then((vm) => {
        if (cancelled) return;
        vmRef.current = vm;
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        // Surface embed failures — previously swallowed, which left
        // the Preview tab visually empty with no explanation.
        setEmbedError(err instanceof Error ? err.message : String(err));
      });

    return () => {
      cancelled = true;
      vmRef.current = null;
      // Clear the outer container's children — removes either the
      // inner target div (if SDK never swapped it) OR the iframe (if
      // SDK did the swap). Either way, React's outer div is empty
      // again before the next render attaches a fresh target.
      try {
        while (outer.firstChild) outer.removeChild(outer.firstChild);
      } catch {
        // Container may already be detached — ignore.
      }
    };
    // scaffoldId in deps so refining the scaffold via chat re-embeds
    // the iframe with the new file set. readOnly in deps so flipping
    // the project from Draft → In Review re-embeds in preview mode.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scaffoldId, framework, readOnly]);

  if (embedError) {
    const openInNewTab = () => {
      // sdk.openProject opens StackBlitz in a new browser tab,
      // bypassing the iframe's CSP / postMessage constraints that
      // caused the embed timeout. Same scaffold contents.
      const filesMap: Record<string, string> = {};
      for (const f of files) {
        filesMap[f.path] = f.content;
      }
      try {
        sdk.openProject(
          {
            title: "Inspira scaffold",
            description: "Generated by Inspira — opened in StackBlitz.",
            template: mapFrameworkToTemplate(framework),
            files: filesMap,
          },
          { newWindow: true },
        );
      } catch {
        // openProject is sync; if even this fails, the user still
        // has the Code tab fallback messaged below.
      }
    };
    return (
      <div
        className="av-code__preview-empty"
        style={{ padding: "32px", textAlign: "center" }}
      >
        <p style={{ marginBottom: 16 }}>
          Preview unavailable — {embedError}.
        </p>
        <p style={{ marginBottom: 16, color: "var(--ink-3)" }}>
          The embedded sandbox couldn't connect (often a Chrome
          extension or third-party iframe restriction). You can open
          the scaffold in a new StackBlitz tab, or switch to Code to
          inspect files directly.
        </p>
        <button
          type="button"
          className="av-empty__cta"
          onClick={openInNewTab}
        >
          Open in StackBlitz tab →
        </button>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className="av-stackblitz"
      style={{ width: "100%", height: "100%" }}
    />
  );
}

function mapFrameworkToTemplate(
  fw?: string | null,
): "node" | "create-react-app" | "angular-cli" | "polymer" | "typescript" | "vue" | "html" {
  if (!fw) return "node";
  const lower = fw.toLowerCase();
  if (lower.includes("vite") || lower.includes("next")) return "node";
  if (lower === "react-cra" || lower === "cra") return "create-react-app";
  if (lower === "angular") return "angular-cli";
  if (lower === "vue") return "vue";
  if (lower === "html") return "html";
  return "node";
}
