"""Drop legacy FK constraints pointing at the deprecated ``projects`` table.

Revision ID: 20260422_0003
Revises: 20260422_0002
Create Date: 2026-04-22

Context
-------

Eight canvas-related tables (``topics``, ``relationships``, ``qna_turns``,
``decisions``, ``context_sources``, ``summary_versions``, ``sessions``,
``artifacts``) inherited a ``FOREIGN KEY(project_id) REFERENCES
projects(project_id)`` clause from the v1 schema. The app switched to
``v2_projects`` as the canonical projects table, but the FK pointers were
never updated. This was latent on SQLite (FKs are off by default there
unless you ``PRAGMA foreign_keys = ON``), but Postgres enforces them — so
every INSERT into any of those tables explodes with:

  psycopg.errors.ForeignKeyViolation: insert or update on table "topics"
  violates foreign key constraint "topics_project_id_fkey"
  DETAIL:  Key (project_id)=(project-4aad54e8da17) is not present in
  table "projects".

That blocks template kickoff, regular kickoff, example-project
instantiation, and every Q&A turn that writes a new topic. Basically the
whole canvas editor is broken on Postgres.

Fix
---

The cleanest thing would be to re-point the FK at ``v2_projects``. That
requires knowing the exact name of the existing constraint (Postgres
autogenerated it as ``<table>_<column>_fkey``) AND it would leave us with
a FK that SQLite still doesn't enforce anyway. Given how many of these
there are, and given that application-level integrity has kept us safe on
SQLite for months, just DROP the legacy FKs. Data is already
app-integrity-managed; we lose nothing and the canvas starts working on
Postgres immediately.

On SQLite, ``ALTER TABLE ... DROP CONSTRAINT`` doesn't exist, but SQLite
also doesn't enforce the FK in the first place — so this migration is a
no-op on SQLite. We detect the dialect and skip cleanly.

Downgrade recreates the FK (Postgres only), preserving reversibility even
though we probably won't ever use it.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "20260422_0003"
down_revision: Union[str, Sequence[str], None] = "20260422_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every (table, constraint_name) pair created by the baseline migration
# that points at the deprecated v1 ``projects`` table. Constraint names
# follow Postgres' default auto-naming: ``<table>_<column>_fkey``.
_LEGACY_FKS: list[tuple[str, str]] = [
    ("sessions", "sessions_project_id_fkey"),
    ("artifacts", "artifacts_project_id_fkey"),
    ("topics", "topics_project_id_fkey"),
    ("relationships", "relationships_project_id_fkey"),
    ("qna_turns", "qna_turns_project_id_fkey"),
    ("decisions", "decisions_project_id_fkey"),
    ("context_sources", "context_sources_project_id_fkey"),
    ("summary_versions", "summary_versions_project_id_fkey"),
]


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # SQLite doesn't enforce FKs and has no ``DROP CONSTRAINT`` syntax,
        # so this migration is a no-op there. The dev bootstrap still
        # contains the FK clause but it has no runtime effect.
        return

    for table, name in _LEGACY_FKS:
        op.execute(
            sa.text(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{name}"')
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # Restore the original FK shapes. Kept for reversibility; in practice
    # we'd rather point the FKs at v2_projects if we re-add them.
    for table, name in _LEGACY_FKS:
        op.execute(
            sa.text(
                f'ALTER TABLE "{table}" '
                f'ADD CONSTRAINT "{name}" '
                f'FOREIGN KEY (project_id) REFERENCES projects(project_id)'
            )
        )
